-- 코드를 입력하세요
SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, round(AVG(R.REVIEW_SCORE), 2) AS REVIEW_SCORE
from REST_REVIEW as R inner join REST_INFO as I
ON R.REST_ID = I.REST_ID
WHERE I.ADDRESS LIKE '서울%'
GROUP BY I.REST_ID
ORDER BY AVG(R.REVIEW_SCORE) DESC, I.FAVORITES DESC