SELECT 
    H.HISTORY_ID,
    ROUND(C.DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE) + 1) * (100 - IFNULL(D.DISCOUNT_RATE, 0)) / 100, 0) AS FEE

FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
JOIN CAR_RENTAL_COMPANY_CAR AS C ON H.CAR_ID = C.CAR_ID

LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS D 
  ON C.CAR_TYPE = D.CAR_TYPE 
  AND D.DURATION_TYPE = (
        CASE 
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 7  THEN '7일 이상'
            ELSE NULL -- 7일 미만은 조인 안 됨 -> DISCOUNT_RATE가 NULL이 됨
        END
  )

WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, H.HISTORY_ID DESC;